### ISSUE TITLE
Add wagmi and rainbowkit

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/wethwrapper-web#40]

**Comment by personnamedmike** [comment]
I'll close this issue since wagmi + rbk has been added. Changes are on branch `40-wagmi-rainbowkit`, but it hasn't been merged with `develop` yet

**Comment by plor** [comment]
Can you open a pull request to track the merging of this branch?

**Comment by personnamedmike** [comment]
I might have closed this issue too soon. I setup wagmi and rainbowkit, but much of the app is broken and I'm troubleshooting it. If we merge my changes, the app will be unusable, other than connecting wallets
