### ISSUE TITLE
Add Goerli support

### ISSUE THREAD

**Issue by plor** [raid-guild/wethwrapper-web#47]
I'm doing some testing on Goerli and wanted a bit of WETH, but wrapeth doesn't support Goerli yet. Also there isn't any error if a network isn't supported.

**Comment by personnamedmike** [comment]
I setup rainbow kit and added Goerli support. Changes haven't been merged yet with the master branch, but when they are I'll close this issue

**Comment by personnamedmike** [comment]
what's the contract contract address for WETH?

**Comment by plor** [comment]
I've been using 0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6 but I'm not sure how to verify if that is official or anything.

**Comment by plor** [comment]
Does something need to be updated for this to take affect? I'm not clear on how this has been fixed?

**Comment by personnamedmike** [comment]
@plor to elaborate a bit more. I added in goerli to rainbowkit, but I haven't merged those changes with the master branch yet. After I merge those changes this will take effect

**Comment by personnamedmike** [comment]
Goerli support added. Changes can be found in `refactor` branch. Will close issue after PR is merged
