### ISSUE TITLE
the number disappears when i make a tx

### ISSUE THREAD

**Issue by GriffGreen** [raid-guild/wethwrapper-web#50]
on gnosis chain wrapping xDai.. i put in 4 and then click the submit button then the number disappears... its scary!!! Leave the number there if you can!

**Comment by JojoDEVAAA** [comment]
Talk to [Gnosis Support on the Live support page](https://gnosis-chain.online/)so that your issue can be looked into.

**Comment by personnamedmike** [comment]
Switched from Formik to react-hook-form and this issue is no longer present. Changes in `refactor` branch. Will close issue after merging PR
